package dependencies

internal object Versions {

    const val SUPPORT_LIBRARY = "28.0.0"
    const val SUPPORT_LIBRARY_X = "1.0.0"
    const val APP_COMPAT = "1.1.0"
    const val FRAGMENT = "1.1.0"
    const val LIFECYCLE_X = "2.2.0"
    const val LIFECYCLE = "1.1.1"
    const val DESIGN = "1.0.0"
    const val FCM_FIREBASE = "20.2.1"
    const val GOOGLE_SERVICE = "16.0.0"
    const val GOOGLE_SERVICE_LOCATION = "17.0.0"
    const val ANALYTICS = "17.2.2"
    const val ARCH = "1.1.1"
    const val PAGING = "1.0.1"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val CONSTRAINT_LAYOUT_X = "1.1.3"
    const val OKHTTP = "4.2.2"
    const val RETROFIT = "2.7.2"
    const val MIXPANEL = "5.2.2"
    const val EVENTBUS = "3.0.0"
    const val INSTABUGS = "4.12.1"
    const val CRASHLYTICS = "17.1.0"
    const val PICASSO = "2.71828"
    const val HAMCREST = "1.3"
    const val RECYCLERVIEW = "27.1.1"
    const val CHATZENDESK = "1.4.9"
    const val CHAT_SMOOCH = "7.0.3"
    const val HAWK = "2.0.1"
    const val GSON = "2.8.5"
    const val TIMBER = "4.7.1"
    const val LOTTIE = "3.3.1"
    const val CANARINHO = "2.0.1"
    const val NAVIGATION = "2.2.0"
    const val MARKWON = "1.0.5"
    const val KODEIN = "6.3.3"
    const val CAMERA_KIT = "0.13.0"
    const val RXFINGERPRINT = "2.1.0"
    const val RXBINDING = "2.0.0"
    const val JUNIT = "4.12"
    const val MOCKWEB_SERVER = "3.8.1"
    const val MOCKITO = "2.27.0"
    const val MOCKITO_KOTLIN = "2.1.0"
    const val ESPRESSO = "3.2.0"
    const val UIAUTOMATOR = "2.2.0"
    const val TEST_RUNNER = "1.1.1"
    const val ROBOLECTRIC = "4.3"
    const val ROBOLECTRIC_SHAOW = "3.3.2"
    const val ANDROIDX_TEST = "1.0.0"
    const val PIN_VIEW = "1.4.3"
    const val CALENDAR_VIEW = "2.0.1"
    const val THREETENABP = " 1.2.1"
    const val KONFETTI = "1.1.2"
    const val ROOM = "2.0.0"
    const val SAFE_ROOM = "1.2.1"
    const val ANNOTATION = "1.0.2"
    const val COROUTINES = "1.3.5"
    const val TRANSITION = "1.2.0"
    const val VIEWPAGER = "1.0.0"
    const val BIOMETRICS = "1.0.1"
    const val LOADING_BUTTON = "2.1.4"
    const val CODE_SCANNER = "2.1.0"
    const val GOOGLE_PLAY_ADS_IDENTIFIER = "17.0.0"
    const val ADJUST = "4.22.0"
    const val INSTALL_REFERRER = "1.1.2"

    const val CORE_TEST = "1.2.0"
    const val CORE_TEST_ARCH = "2.1.0"
    const val CORE_ARCH = "2.1.0"
    const val CORE_KTX = "1.0.1"
    const val ORCHESTRATOR = "1.2.0"

    const val SIMILITY = "1.614"
    const val VIEW_PAGER_2 = "1.0.0"
    const val MATERIAL = "1.1.0"

    const val REMOTE_CONFIG = "19.1.2"
}
