@file:JvmName("DatePatterns")

package org.js.denisvieira.featureplayground.commons.formatter

const val BRAZIL_PATTERN_DAY_AND_MONTH = "dd/MM"
const val BRAZIL_PATTERN_MONTH_AND_YEAR = "MM/yyyy"
const val BRAZIL_PATTERN_DAY_AND_MONTH_AND_YEAR = "dd/MM/yyyy"
const val BRAZIL_PATTERN_MM_YY = "MM/yy"
const val BRAZIL_PATTERN_DAY_AND_MONTH_YEAR_HOUR_MINUTES = "dd/MM/yyyy, HH:mm"
const val BRAZIL_PATTERN_DAY_AND_MONTH_HOUR_MINUTES = "dd/MMMM, HH:mm"
const val SLASH_PATTERN_DAY_MONTH_AND_YEAR = "dd/MM/yy"
const val SLASH_PATTERN_DAY_MONTH_AND_YEAR_FOUR = "dd/MM/yyyy"
const val DOTS_PATTERN_DAY_MONTH_AND_YEAR = "dd.MM.yyyy"
const val API_PATTERN_DATE_AND_TIME = "yyyy-MM-dd'T'HH:mm:ss.SSS"
const val API_PATTERN_DATE_TIME_AND_SECONDS = "yyyy-MM-dd'T'HH:mm:ss"
const val LITERAL_DATE_DAY_MONTH_EXTENSIBLE = "dd' de 'MMMM"
const val LITERAL_DATE_DAY_MONTH_YEAR_EXTENSIBLE = "dd' de 'MMMM' de 'yyyy"
const val DAY_PATTERN = "dd"
const val LITERAL_DATE_DAY_MONTH = "dd' 'MMMM"
const val UTC = "UTC"
const val LITERAL_DATE_MONTH_YEAR = "MMMM' 'yyyy"
const val API_PATTERN_DATE_TIME_AND_SECONDS_ZONE = "yyyy-MM-dd'T'HH:mm:ss'Z'"
const val API_PATTERN_DATE_TIME_AND_SECONDS_AND_MILLISECONDS_ZONE = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
const val API_PATTERN = "yyyy-MM-dd"
const val MONTH = "MM"
const val LITERAL_DATE_DAY_MONTH_DAY_OF_WEEK = "dd' de 'MMMM', 'EEEE"
const val LITERAL_MONTH_PATTERN = "MMMM"
const val LITERAL_DATE_DAY_MONTH_ACCESSIBILITY = "d' de 'MMMM"

internal const val LITERAL_DATE_DAY_OF_WEEK_AND_DAY = "EEEE', dia' dd"
internal const val DEFAULT_MONTH_INPUT_PATTERN = "MMM"
internal const val DAY_OF_WEEK_PATTERN = "EEEE"
internal const val API_PATTERN_YYMM = "yyMM"
